package com.fersaiyan.cyanbridge.bridge.runtimes.mentra

import android.util.Log
import org.json.JSONObject
import java.io.OutputStream
import java.util.concurrent.ConcurrentHashMap

/**
 * Manages active MentraOS app sessions connected to the local relay.
 *
 * Each session represents a connected app that can send display commands
 * and optionally subscribe to input events. Sessions are identified by
 * a unique session ID (generated by the app or the relay).
 *
 * In the simplified HTTP mode, sessions persist only for the duration
 * of a single HTTP connection. For persistent streaming (real input events),
 * a WebSocket upgrade is needed.
 */
class MentraSessionManager {

    companion object {
        private const val TAG = "MentraSessionManager"
    }

    /**
     * A connected MentraOS app session.
     *
     * @property sessionId   Unique identifier for the session.
     * @property packageName Name of the connected app (e.g. com.example.myapp).
     * @property outputStream Stream for sending messages back to the app.
     * @property subscriptions Set of input stream types the app has subscribed to.
     */
    data class Session(
        val sessionId: String,
        val packageName: String,
        val outputStream: OutputStream,
        val subscriptions: MutableSet<String> = mutableSetOf(),
    )

    private val sessions = ConcurrentHashMap<String, Session>()

    /**
     * Register a new session.
     */
    fun addSession(session: Session) {
        sessions[session.sessionId] = session
        Log.i(TAG, "Session added: ${session.packageName} (${session.sessionId}) — ${sessions.size} active")
    }

    /**
     * Remove a session by ID.
     */
    fun removeSession(sessionId: String) {
        val removed = sessions.remove(sessionId)
        if (removed != null) {
            Log.i(TAG, "Session removed: ${removed.packageName} ($sessionId) — ${sessions.size} active")
        }
    }

    /**
     * Look up a session by ID.
     */
    fun getSession(sessionId: String): Session? = sessions[sessionId]

    /**
     * Return all active sessions.
     */
    fun getAllSessions(): List<Session> = sessions.values.toList()

    /**
     * Broadcast a JSON message to all connected sessions.
     * Sessions whose output stream throws are automatically removed.
     */
    fun broadcastMessage(message: JSONObject) {
        val payload = message.toString()
        val deadSessions = mutableListOf<String>()

        for ((id, session) in sessions) {
            try {
                session.outputStream.write(payload.toByteArray(Charsets.UTF_8))
                session.outputStream.flush()
            } catch (e: Exception) {
                Log.w(TAG, "Failed to send to session $id, removing: ${e.message}")
                deadSessions.add(id)
            }
        }

        deadSessions.forEach { sessions.remove(it) }
    }

    /**
     * Remove all sessions.
     */
    fun clear() {
        val count = sessions.size
        sessions.clear()
        Log.i(TAG, "All sessions cleared ($count removed)")
    }
}
